"""""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""""

count = 0
nterms = 15
n1 = 1
n2 = 2
while count < nterms:
    #print(n1)
    nth = n1 + n2
    if n1 % 2 ==0:
        print("Even: ", n1)
    #update values
    n1 = n2
    n2 = nth
    count +=1
